### PR TITLE
Fix protocol errors triggered by new clients after task state

### LINKED ISSUE #114: Subsequent responder handshakes trigger a protocol error
When a new responder connects, not only is the `new-responder` message being ignored, but also the responder that is trying to initiate a handshake triggers a protocol error because the initiator cannot find the responder in its map of responders.

Unfortunately, this implementation of the client has not been designed to fully reset its state to be able to do another handshake. The proposed solution is to drop the responder.

---

(Former description)

~~An initiator dropping a responder currently expects to receive no further messages from that responder. However, a message towards the initiator can already be in flight and cannot be prevented to be received. Thus, we must not treat this as a protocol error.~~

### PR DESCRIPTION
**Pull request by lgrahl**
With this PR we handle `new-initiator` and `new-responder` after a peer handshake properly (somewhat). Resolves #114.

An initiator now simply drops new responders when it has already completed the handshake with another responder.

A responder now closes the connection when a new initiator connects after it has already completed a handshake with a previous initiator.

Note that this deviates from the intention of the specification to allow for more than one connection towards a responder over the same WebSocket connection. But resolving this would be far from trivial.

---

Also makes use of console logging groups and thereby significantly improves readability. What the heck, we found a use case! :tada:

### CODE REVIEW

File: src/signaling/initiator.ts [hunk 1]
```diff
@@ -303,6 +303,27 @@ export class InitiatorSignaling extends Signaling {
...
+     * completed.
+     *
+     * Note: This deviates from the intention of the specification to allow
+     *       for more than one connection towards a responder over the same
+     *       WebSocket connection.
+     */
+    protected onUnhandledSignalingServerMessage(msg: saltyrtc.Message): void {
+        if (msg.type === 'new-responder') {
+            try {
+                this.log.debug(this.logTag, 'Received new-responder');
```
Comment (dbrgn) [inline src/signaling/initiator.ts]: If you want to be consistent with log messages in `onSignalingMessage`, append " message" to the log. Same for the responder.
